---
- hosts: wordpress_servers
#- hosts: zone_wordpress_servers
  vars:
    keep_files: 6
    excluded_plugins:
      - elementor-pro
      - vm_wp  
  gather_facts: no
  become: no
  pre_tasks:
  - name: Initial setup task that runs first
    ansible.builtin.debug:
      msg: "Running initial setup tasks before everything else."
    tags: [ backup ]

  - name: Get current date on machine where playbook is run
    set_fact:
      local_date: "{{ lookup('pipe', 'date +%Y-%m-%d') }}_1"
    delegate_to: localhost
    run_once: true 
    tags: [ backup ]
  roles:
#    - role: database_backup
#      tags: [ backup ]
#    - role: files_backup
#      tags: [ backup ]
  tasks:
    - name: Remove Ansible footer plugin
      file:
       path: "{{ wp_path }}/wp-content/mu-plugins/ansible-footer.php"
       state: absent
    - name: Remove mu-plugins Directory
      file:
        path: "{{ wp_path }}/wp-content/mu-plugins"
        state: absent
