---
- hosts: wordpress_servers
  serial: 1
#- hosts: zone_wordpress_servers
  vars:
    keep_files: 6
    wp_options:
      updraft_dir: "../../updraft"
      blogdescription: ""  
  gather_facts: no
  become: no
  pre_tasks:
  - name: Initial setup task that runs first
    ansible.builtin.debug:
      msg: "Running initial setup tasks before everything else."
    tags: [ backup ]

  - name: Get current date on machine where playbook is run
    set_fact:
      local_date: "{{ lookup('pipe', 'date +%Y-%m-%d') }}_1"
    delegate_to: localhost
    run_once: true 
    tags: [ backup ]
  roles:
    - role: database_backup
      tags: [ backup ]
    - role: files_backup
      tags: [ backup ]

  tasks:
    - name: Create updraft directory (example if You need directory)
      ansible.builtin.file:
        path: "{{ wp_path }}/wp-includes/{{ wp_options.updraft_dir }}"
        state: directory
        mode: "0755"
      when:
        - wp_options is defined
        - wp_options.updraft_dir is defined
        - wp_options.updraft_dir | length > 0

    - name: Update WordPress options (loop from variable wp_opions)
      ansible.builtin.command:
        argv:
          - wp
          - option
          - update
          - "{{ item.key }}"
          - "{{ item.value }}"
      args:
        chdir: "{{ wp_path }}"
      loop: "{{ wp_options | dict2items }}"
      when:
        - item.value is not none
        - item.value | string | length > 0
    
