[defaults]
[restore_servers]
www.domeen1.ee ansible_ssh_host=domeen1.ee ansible_user=virt1111 ansible_python_interpreter=/usr/bin/python3.13
[zone_wordpress_servers]
www.tappsportlased.ee ansible_ssh_host=tappsportlased.ee ansible_user=virt42779 ansible_python_interpreter=/usr/bin/python3.13
www.sebramaja.ee ansible_ssh_host=sebramaja.ee ansible_user=virt83649 ansible_python_interpreter=/usr/bin/python3.13
[veebimajutus_wordpress_servers]
steelroof.ee ansible_ssh_host=steelroof.ee ansible_user=vhost70221ssh ansible_port=1022 ansible_python_interpreter=/usr/local/bin/python3.14
kipiteam.com ansible_ssh_host=kipiteam.com ansible_user=vhost103231ssh ansible_port=1022 ansible_python_interpreter=/usr/local/bin/python3.14
[wordpress_servers:children]
zone_wordpress_servers
veebimajutus_wordpress_servers
