[defaults]
[restore_servers]
www.domeen1.ee ansible_ssh_host=domeen1.ee ansible_user=virt1111 ansible_python_interpreter=/usr/bin/python3.8
[zone_wordpress_servers]
www.domeen1.ee ansible_ssh_host=domeen1.ee ansible_user=virt1111 ansible_python_interpreter=/usr/bin/python3.8
www.domeen2.ee ansible_ssh_host=domeen2.ee ansible_user=virt2222 ansible_python_interpreter=/usr/bin/python3.8
[veebimajutus_wordpress_servers]
domeen3.ee ansible_ssh_host=domeen3.ee ansible_user=vhost3333ssh ansible_port=1022 ansible_python_interpreter=/usr/local/bin/python3.11
domeen4.com ansible_ssh_host=domeen4.com ansible_user=vhost4444ssh ansible_port=1022 ansible_python_interpreter=/usr/local/bin/python3.11
[wordpress_servers:children]
zone_wordpress_servers
veebimajutus_wordpress_servers
