---
# tasks file for roles/files_backup
- name: "Backup files"
  command: "tar --exclude wp-content/cache/* -C {{ htdocsfiles_path }} -cf {{ backup_path }}/{{ item }}_{{ local_date }}.tar {{ item }}"
  with_items:
    - "htdocs"

# deleete older files direcory
- name: Find all files in the specified directory
  find:
    paths: "{{ backup_path }}"
    file_type: file
  register: files_found

- name: Sort files by modification time, newest first
  set_fact:
    sorted_files: "{{ files_found.files | sort(attribute='mtime', reverse=true) }}"

- name: Delete files if more than four exist
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ sorted_files[keep_files:] }}"
  when: sorted_files | length > keep_files

