---
# tasks file for roles/files_backup
- name: Backup files
  ansible.builtin.command: >
    tar
    --warning=no-file-changed
    --exclude=htdocs/wp-content/cache/*
    --exclude=htdocs/wp-content/uploads/*/*.tmp
    --exclude=htdocs/wp-content/debug.log
    --exclude=htdocs/wp-content/upgrade/*
    --exclude=htdocs/wp-content/ai1wm-backups/*
    --exclude=htdocs/wp-content/updraft/*
    -C {{ htdocsfiles_path }}
    -cf {{ backup_path }}/{{ item }}_{{ local_date }}.tar
    {{ item }}
  loop:
    - htdocs
  register: tar_backup
  failed_when: tar_backup.rc not in [0, 1]


# deleete older files direcory
- name: Find all files in the specified directory
  find:
    paths: "{{ backup_path }}"
    file_type: file
  register: files_found

- name: Sort files by modification time, newest first
  set_fact:
    sorted_files: "{{ files_found.files | sort(attribute='mtime', reverse=true) }}"

- name: Delete files if more than four exist
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ sorted_files[keep_files:] }}"
  when: sorted_files | length > keep_files

